const icons: { [key: string]: string } = {
    animation: '/images/content/skills/animation.svg',
    array: '/images/content/skills/array.svg',
    asynchronous: '/images/content/skills/asynchronous.svg',
    auto: '/images/content/skills/auto.svg',
    brouser: '/images/content/skills/brouser.svg',
    bug: '/images/content/skills/bug.svg',
    css: '/images/content/skills/css.svg',
    dom: '/images/content/skills/dom.svg',
    event: '/images/content/skills/event.svg',
    form: '/images/content/skills/form.svg',
    func: '/images/content/skills/func.svg',
    github: '/images/content/skills/github.svg',
    grid: '/images/content/skills/grid.svg',
    html: '/images/content/skills/html.svg',
    jquery: '/images/content/skills/jquery.svg',
    js: '/images/content/skills/js.svg',
    obj: '/images/content/skills/obj.svg',
    oop: '/images/content/skills/oop.svg',
    other: '/images/content/skills/other.svg',
    password: '/images/content/skills/password.svg',
    pattern: '/images/content/skills/pattern.svg',
    php: '/images/content/skills/php.svg',
    react: '/images/content/skills/react.svg',
    redux: '/images/content/skills/redux.svg',
    responsive: '/images/content/skills/responsive.svg',
    route: '/images/content/skills/route.svg',
    sass: '/images/content/skills/sass.svg',
    storage: '/images/content/skills/storage.svg',
    ts: '/images/content/skills/ts.svg',
    wordpress: '/images/content/skills/wordpress.svg',
    saga: '/images/content/skills/saga.svg',
    hooks: '/images/content/skills/hooks.svg',
    file: '/images/content/skills/file.svg',
    express: '/images/content/skills/form.svg',
    next: '/images/content/skills/next.svg',
    mongo: '/images/content/skills/mongo.svg',
};

export default icons;
